import { useState } from 'react'

interface FormData {
  name: string
  title: string
  email: string
  phone: string
  location: string
  experience: string
  education: string
  skills: string
  summary: string
}

const templates = [
  { id: 'modern', name: '现代简约', color: 'blue' },
  { id: 'professional', name: '专业经典', color: 'gray' },
  { id: 'creative', name: '创意设计', color: 'purple' },
  { id: 'tech', name: '科技极客', color: 'green' },
]

function ResumeGenerator() {
  const [formData, setFormData] = useState<FormData>({
    name: '',
    title: '',
    email: '',
    phone: '',
    location: '',
    experience: '',
    education: '',
    skills: '',
    summary: '',
  })
  const [selectedTemplate, setSelectedTemplate] = useState('modern')
  const [generatedResume, setGeneratedResume] = useState('')
  const [loading, setLoading] = useState(false)
  const [isEditing, setIsEditing] = useState(false)
  const [editedResume, setEditedResume] = useState('')
  const [showSuccess, setShowSuccess] = useState(false)

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value })
  }

  const handleGenerate = () => {
    if (!formData.name || !formData.experience) {
      alert('请填写姓名和工作经验')
      return
    }

    setLoading(true)

    // 模拟 AI 生成简历
    setTimeout(() => {
      const resume = generateResumeFromTemplate(formData, selectedTemplate)
      setGeneratedResume(resume)
      setEditedResume(resume)
      setLoading(false)
      setShowSuccess(true)
      setTimeout(() => setShowSuccess(false), 3000)
    }, 2000)
  }

  const generateResumeFromTemplate = (data: FormData, template: string) => {
    const skills = data.skills.split(',').map(s => s.trim()).filter(s => s)

    if (template === 'modern') {
      return `
# ${data.name}
**${data.title || '高级工程师'}**

📧 ${data.email} | 📱 ${data.phone} | 📍 ${data.location}

---

## 💡 个人简介

${data.summary || '富有经验的工程师，专注于技术创新和团队协作。'}

---

## 🛠️ 核心技能

${skills.map(skill => `- **${skill}**`).join('\n')}

---

## 💼 工作经验

${data.experience}

---

## 🎓 教育背景

${data.education}

---

*简历由 Gitvim AI 生成*
      `.trim()
    } else if (template === 'professional') {
      return `
═══════════════════════════════════════
              ${data.name}
          ${data.title || '高级工程师'}
═══════════════════════════════════════

联系方式
───────────────────────────────────────
邮箱：${data.email}
电话：${data.phone}
地点：${data.location}

职业概述
───────────────────────────────────────
${data.summary || '富有经验的工程师，专注于技术创新和团队协作。'}

专业技能
───────────────────────────────────────
${skills.join(' | ')}

工作经历
───────────────────────────────────────
${data.experience}

教育背景
───────────────────────────────────────
${data.education}
      `.trim()
    } else if (template === 'creative') {
      return `
✦ ${data.name} ✦
━━━━━━━━━━━━━━━━━━━━━━
  ${data.title || '创意工程师'}

💌 ${data.email}
📱 ${data.phone}
🌍 ${data.location}

━━━━━━━━━━━━━━━━━━━━━━

✨ 关于我
${data.summary || '富有经验的工程师，专注于技术创新和团队协作。'}

━━━━━━━━━━━━━━━━━━━━━━

🎨 技能树
${skills.map(skill => `▸ ${skill}`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━

💼 经历
${data.experience}

━━━━━━━━━━━━━━━━━━━━━━

🎓 教育
${data.education}
      `.trim()
    } else {
      // Tech template
      return `
┌─────────────────────────────────────┐
│  ${data.name.padEnd(30)}│
│  ${data.title.padEnd(30)}│
└─────────────────────────────────────┘

> CONTACT
  Email: ${data.email}
  Phone: ${data.phone}
  Location: ${data.location}

> ABOUT
  ${data.summary || '富有经验的工程师，专注于技术创新和团队协作。'}

> SKILLS
${skills.map(skill => `  [${skill}]`).join(' ')}

> EXPERIENCE
  ${data.experience.replace(/\n/g, '\n  ')}

> EDUCATION
  ${data.education}

---
Generated by Gitvim AI
      `.trim()
    }
  }

  const handleExport = (format: 'pdf' | 'word') => {
    if (format === 'pdf') {
      exportToPDF()
    } else {
      exportToWord()
    }
  }

  const exportToPDF = async () => {
    // 动态导入 html2pdf.js
    const html2pdf = (await import('html2pdf.js')).default
    
    // 创建临时容器
    const element = document.createElement('div')
    element.innerHTML = generatedResume.replace(/\n/g, '<br>')
    element.style.padding = '40px'
    element.style.fontFamily = 'Arial, sans-serif'
    element.style.fontSize = '14px'
    element.style.lineHeight = '1.6'
    
    const opt = {
      margin: 10,
      filename: `${formData.name}-简历.pdf`,
      image: { type: 'jpeg' as const, quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'mm' as const, format: 'a4' as const, orientation: 'portrait' as const }
    }
    
    html2pdf().set(opt).from(element).save()
  }

  const exportToWord = async () => {
    // 动态导入 docx 库
    const { Document, Packer, Paragraph, TextRun, HeadingLevel } = await import('docx')
    const { saveAs } = await import('file-saver')
    
    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          new Paragraph({
            text: formData.name,
            heading: HeadingLevel.TITLE,
          }),
          new Paragraph({
            text: formData.title,
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `📧 ${formData.email} | 📱 ${formData.phone} | 📍 ${formData.location}`,
                size: 20,
              }),
            ],
          }),
          new Paragraph({
            text: "个人简介",
            heading: HeadingLevel.HEADING_2,
          }),
          new Paragraph({
            text: formData.summary || '富有经验的工程师，专注于技术创新和团队协作。',
          }),
          new Paragraph({
            text: "核心技能",
            heading: HeadingLevel.HEADING_2,
          }),
          ...formData.skills.split(',').map(skill => 
            new Paragraph({
              text: skill.trim(),
              bullet: { level: 0 }
            })
          ),
          new Paragraph({
            text: "工作经验",
            heading: HeadingLevel.HEADING_2,
          }),
          new Paragraph({
            text: formData.experience,
          }),
          new Paragraph({
            text: "教育背景",
            heading: HeadingLevel.HEADING_2,
          }),
          new Paragraph({
            text: formData.education,
          }),
        ],
      }],
    })
    
    Packer.toBlob(doc).then(blob => {
      saveAs(blob, `${formData.name}-简历.docx`)
    })
  }

  return (
    <div className="space-y-6">
      {/* 成功提示 */}
      {showSuccess && (
        <div className="bg-gradient-to-r from-green-400 to-emerald-500 text-white px-6 py-4 rounded-xl shadow-lg animate-fade-in flex items-center gap-3">
          <span className="text-2xl">✅</span>
          <span className="font-medium">简历生成成功！</span>
        </div>
      )}

      {/* 模板选择 */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-3">
          选择简历模板
        </label>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {templates.map((template) => (
            <button
              key={template.id}
              onClick={() => setSelectedTemplate(template.id)}
              className={`p-6 rounded-2xl border-2 transition-all duration-300 transform hover:scale-105 hover:shadow-xl ${
                selectedTemplate === template.id
                  ? 'border-blue-500 bg-gradient-to-br from-blue-50 to-purple-50 shadow-lg scale-105'
                  : 'border-gray-200 hover:border-gray-300 bg-white/50'
              }`}
            >
              <div className={`text-4xl mb-3 ${
                selectedTemplate === template.id ? 'animate-bounce-soft' : ''
              }`}>
                {template.id === 'modern' && '📄'}
                {template.id === 'professional' && '📋'}
                {template.id === 'creative' && '🎨'}
                {template.id === 'tech' && '💻'}
              </div>
              <div className={`font-semibold ${
                selectedTemplate === template.id 
                  ? 'bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent'
                  : 'text-gray-700'
              }`}>
                {template.name}
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* 基本信息 */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            姓名 *
          </label>
          <input
            type="text"
            name="name"
            value={formData.name}
            onChange={handleChange}
            className="input-field"
            placeholder="张三"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            职位头衔
          </label>
          <input
            type="text"
            name="title"
            value={formData.title}
            onChange={handleChange}
            className="input-field"
            placeholder="高级 Python 工程师"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            邮箱
          </label>
          <input
            type="email"
            name="email"
            value={formData.email}
            onChange={handleChange}
            className="input-field"
            placeholder="zhangsan@example.com"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            电话
          </label>
          <input
            type="tel"
            name="phone"
            value={formData.phone}
            onChange={handleChange}
            className="input-field"
            placeholder="138-0000-0000"
          />
        </div>
        <div className="md:col-span-2">
          <label className="block text-sm font-medium text-gray-700 mb-2">
            所在城市
          </label>
          <input
            type="text"
            name="location"
            value={formData.location}
            onChange={handleChange}
            className="input-field"
            placeholder="北京"
          />
        </div>
      </div>

      {/* 技能 */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          核心技能（逗号分隔）
        </label>
        <input
          type="text"
          name="skills"
          value={formData.skills}
          onChange={handleChange}
          className="input-field"
          placeholder="Python, Django, PostgreSQL, Docker, 团队管理"
        />
      </div>

      {/* 个人简介 */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          个人简介
        </label>
        <textarea
          name="summary"
          value={formData.summary}
          onChange={handleChange}
          className="input-field h-24 resize-none"
          placeholder="5年Python开发经验，专注于后端架构设计和性能优化..."
        />
      </div>

      {/* 工作经验 */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          工作经验 *
        </label>
        <textarea
          name="experience"
          value={formData.experience}
          onChange={handleChange}
          className="input-field h-40 resize-none"
          placeholder={`高级工程师 | ABC 公司 | 2020-至今
- 负责核心系统架构设计，提升系统性能 40%
- 带领 5 人团队完成微服务改造
- 优化数据库查询，响应时间降低 60%

工程师 | XYZ 公司 | 2018-2020
- 开发自动化测试框架，覆盖率从 30% 提升到 85%
- ...`}
        />
      </div>

      {/* 教育背景 */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          教育背景
        </label>
        <textarea
          name="education"
          value={formData.education}
          onChange={handleChange}
          className="input-field h-24 resize-none"
          placeholder="计算机科学学士 | 北京大学 | 2014-2018"
        />
      </div>

      {/* 生成按钮 */}
      <div className="flex gap-4">
        <button
          onClick={handleGenerate}
          disabled={loading}
          className="btn-primary flex-1 text-lg py-4 relative overflow-hidden group"
        >
          {loading ? (
            <span className="flex items-center justify-center gap-3">
              <span className="inline-block w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></span>
              生成中...
            </span>
          ) : (
            <span className="relative z-10">
              ✨ 生成简历
            </span>
          )}
          {!loading && (
            <div className="absolute inset-0 bg-gradient-to-r from-purple-600 to-pink-600 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
          )}
        </button>
      </div>

      {/* 生成的简历预览 */}
      {generatedResume && (
        <div className="space-y-4 animate-fade-in">
          <div className="flex items-center justify-between">
            <h3 className="font-semibold text-gray-900 text-xl">
              {isEditing ? '✏️ 编辑简历' : '📄 生成的简历预览'}
            </h3>
            <div className="flex gap-2 flex-wrap">
              {!isEditing ? (
                <>
                  <button
                    onClick={() => setIsEditing(true)}
                    className="px-4 py-2 text-sm bg-gradient-to-r from-yellow-400 to-orange-500 hover:from-yellow-500 hover:to-orange-600 text-white rounded-lg transition-all duration-300 shadow-md hover:shadow-lg transform hover:scale-105"
                  >
                    ✏️ 编辑
                  </button>
                  <button
                    onClick={() => {
                      navigator.clipboard.writeText(generatedResume)
                      alert('已复制到剪贴板')
                    }}
                    className="px-4 py-2 text-sm bg-gray-100 hover:bg-gray-200 rounded-lg transition-all duration-300"
                  >
                    📋 复制
                  </button>
                  <button
                    onClick={() => handleExport('pdf')}
                    className="px-4 py-2 text-sm bg-gradient-to-r from-red-500 to-pink-500 hover:from-red-600 hover:to-pink-600 text-white rounded-lg transition-all duration-300 shadow-md hover:shadow-lg transform hover:scale-105"
                  >
                    📄 导出 PDF
                  </button>
                  <button
                    onClick={() => handleExport('word')}
                    className="px-4 py-2 text-sm bg-gradient-to-r from-blue-500 to-indigo-500 hover:from-blue-600 hover:to-indigo-600 text-white rounded-lg transition-all duration-300 shadow-md hover:shadow-lg transform hover:scale-105"
                  >
                    📝 导出 Word
                  </button>
                </>
              ) : (
                <>
                  <button
                    onClick={() => {
                      setGeneratedResume(editedResume)
                      setIsEditing(false)
                    }}
                    className="px-4 py-2 text-sm bg-gradient-to-r from-green-500 to-emerald-500 hover:from-green-600 hover:to-emerald-600 text-white rounded-lg transition-all duration-300 shadow-md hover:shadow-lg transform hover:scale-105"
                  >
                    ✅ 保存
                  </button>
                  <button
                    onClick={() => {
                      setEditedResume(generatedResume)
                      setIsEditing(false)
                    }}
                    className="px-4 py-2 text-sm bg-gray-100 hover:bg-gray-200 rounded-lg transition-all duration-300"
                  >
                    ❌ 取消
                  </button>
                </>
              )}
            </div>
          </div>
          {isEditing ? (
            <textarea
              value={editedResume}
              onChange={(e) => setEditedResume(e.target.value)}
              className="w-full h-[600px] bg-white/80 backdrop-blur-sm rounded-2xl p-6 font-mono text-sm border-2 border-gray-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 resize-y shadow-lg"
              placeholder="编辑你的简历..."
            />
          ) : (
            <div className="bg-gradient-to-br from-gray-50 to-blue-50 rounded-2xl p-8 whitespace-pre-wrap font-mono text-sm max-h-[600px] overflow-y-auto border-2 border-gray-200 shadow-lg">
              {generatedResume}
            </div>
          )}
        </div>
      )}
    </div>
  )
}

export default ResumeGenerator
