import { useState } from 'react'

interface FormData {
  name: string
  title: string
  email: string
  phone: string
  location: string
  experience: string
  education: string
  skills: string
  summary: string
}

const templates = [
  { id: 'modern', name: '现代简约', color: 'blue' },
  { id: 'professional', name: '专业经典', color: 'gray' },
  { id: 'creative', name: '创意设计', color: 'purple' },
  { id: 'tech', name: '科技极客', color: 'green' },
]

function ResumeGenerator() {
  const [formData, setFormData] = useState<FormData>({
    name: '',
    title: '',
    email: '',
    phone: '',
    location: '',
    experience: '',
    education: '',
    skills: '',
    summary: '',
  })
  const [selectedTemplate, setSelectedTemplate] = useState('modern')
  const [generatedResume, setGeneratedResume] = useState('')
  const [loading, setLoading] = useState(false)

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value })
  }

  const handleGenerate = () => {
    if (!formData.name || !formData.experience) {
      alert('请填写姓名和工作经验')
      return
    }

    setLoading(true)

    // 模拟 AI 生成简历
    setTimeout(() => {
      const resume = generateResumeFromTemplate(formData, selectedTemplate)
      setGeneratedResume(resume)
      setLoading(false)
    }, 2000)
  }

  const generateResumeFromTemplate = (data: FormData, template: string) => {
    const skills = data.skills.split(',').map(s => s.trim()).filter(s => s)

    if (template === 'modern') {
      return `
# ${data.name}
**${data.title || '高级工程师'}**

📧 ${data.email} | 📱 ${data.phone} | 📍 ${data.location}

---

## 💡 个人简介

${data.summary || '富有经验的工程师，专注于技术创新和团队协作。'}

---

## 🛠️ 核心技能

${skills.map(skill => `- **${skill}**`).join('\n')}

---

## 💼 工作经验

${data.experience}

---

## 🎓 教育背景

${data.education}

---

*简历由 Gitvim AI 生成*
      `.trim()
    } else if (template === 'professional') {
      return `
═══════════════════════════════════════
              ${data.name}
          ${data.title || '高级工程师'}
═══════════════════════════════════════

联系方式
───────────────────────────────────────
邮箱：${data.email}
电话：${data.phone}
地点：${data.location}

职业概述
───────────────────────────────────────
${data.summary || '富有经验的工程师，专注于技术创新和团队协作。'}

专业技能
───────────────────────────────────────
${skills.join(' | ')}

工作经历
───────────────────────────────────────
${data.experience}

教育背景
───────────────────────────────────────
${data.education}
      `.trim()
    } else if (template === 'creative') {
      return `
✦ ${data.name} ✦
━━━━━━━━━━━━━━━━━━━━━━
  ${data.title || '创意工程师'}

💌 ${data.email}
📱 ${data.phone}
🌍 ${data.location}

━━━━━━━━━━━━━━━━━━━━━━

✨ 关于我
${data.summary || '富有经验的工程师，专注于技术创新和团队协作。'}

━━━━━━━━━━━━━━━━━━━━━━

🎨 技能树
${skills.map(skill => `▸ ${skill}`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━

💼 经历
${data.experience}

━━━━━━━━━━━━━━━━━━━━━━

🎓 教育
${data.education}
      `.trim()
    } else {
      // Tech template
      return `
┌─────────────────────────────────────┐
│  ${data.name.padEnd(30)}│
│  ${data.title.padEnd(30)}│
└─────────────────────────────────────┘

> CONTACT
  Email: ${data.email}
  Phone: ${data.phone}
  Location: ${data.location}

> ABOUT
  ${data.summary || '富有经验的工程师，专注于技术创新和团队协作。'}

> SKILLS
${skills.map(skill => `  [${skill}]`).join(' ')}

> EXPERIENCE
  ${data.experience.replace(/\n/g, '\n  ')}

> EDUCATION
  ${data.education}

---
Generated by Gitvim AI
      `.trim()
    }
  }

  const handleExport = (format: 'pdf' | 'word') => {
    alert(`${format.toUpperCase()} 导出功能开发中...\n\n当前可以：\n1. 复制生成的简历\n2. 粘贴到 Word/Pages\n3. 导出为 PDF`)
  }

  return (
    <div className="space-y-6">
      {/* 模板选择 */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          选择简历模板
        </label>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {templates.map((template) => (
            <button
              key={template.id}
              onClick={() => setSelectedTemplate(template.id)}
              className={`p-4 rounded-lg border-2 transition-all ${
                selectedTemplate === template.id
                  ? 'border-primary-500 bg-primary-50'
                  : 'border-gray-200 hover:border-gray-300'
              }`}
            >
              <div className={`text-2xl mb-2 text-${template.color}-500`}>
                {template.id === 'modern' && '📄'}
                {template.id === 'professional' && '📋'}
                {template.id === 'creative' && '🎨'}
                {template.id === 'tech' && '💻'}
              </div>
              <div className="text-sm font-medium">{template.name}</div>
            </button>
          ))}
        </div>
      </div>

      {/* 基本信息 */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            姓名 *
          </label>
          <input
            type="text"
            name="name"
            value={formData.name}
            onChange={handleChange}
            className="input-field"
            placeholder="张三"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            职位头衔
          </label>
          <input
            type="text"
            name="title"
            value={formData.title}
            onChange={handleChange}
            className="input-field"
            placeholder="高级 Python 工程师"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            邮箱
          </label>
          <input
            type="email"
            name="email"
            value={formData.email}
            onChange={handleChange}
            className="input-field"
            placeholder="zhangsan@example.com"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            电话
          </label>
          <input
            type="tel"
            name="phone"
            value={formData.phone}
            onChange={handleChange}
            className="input-field"
            placeholder="138-0000-0000"
          />
        </div>
        <div className="md:col-span-2">
          <label className="block text-sm font-medium text-gray-700 mb-2">
            所在城市
          </label>
          <input
            type="text"
            name="location"
            value={formData.location}
            onChange={handleChange}
            className="input-field"
            placeholder="北京"
          />
        </div>
      </div>

      {/* 技能 */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          核心技能（逗号分隔）
        </label>
        <input
          type="text"
          name="skills"
          value={formData.skills}
          onChange={handleChange}
          className="input-field"
          placeholder="Python, Django, PostgreSQL, Docker, 团队管理"
        />
      </div>

      {/* 个人简介 */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          个人简介
        </label>
        <textarea
          name="summary"
          value={formData.summary}
          onChange={handleChange}
          className="input-field h-24 resize-none"
          placeholder="5年Python开发经验，专注于后端架构设计和性能优化..."
        />
      </div>

      {/* 工作经验 */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          工作经验 *
        </label>
        <textarea
          name="experience"
          value={formData.experience}
          onChange={handleChange}
          className="input-field h-40 resize-none"
          placeholder={`高级工程师 | ABC 公司 | 2020-至今
- 负责核心系统架构设计，提升系统性能 40%
- 带领 5 人团队完成微服务改造
- 优化数据库查询，响应时间降低 60%

工程师 | XYZ 公司 | 2018-2020
- 开发自动化测试框架，覆盖率从 30% 提升到 85%
- ...`}
        />
      </div>

      {/* 教育背景 */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          教育背景
        </label>
        <textarea
          name="education"
          value={formData.education}
          onChange={handleChange}
          className="input-field h-24 resize-none"
          placeholder="计算机科学学士 | 北京大学 | 2014-2018"
        />
      </div>

      {/* 生成按钮 */}
      <div className="flex gap-4">
        <button
          onClick={handleGenerate}
          disabled={loading}
          className="btn-primary flex-1"
        >
          {loading ? '生成中...' : '✨ 生成简历'}
        </button>
      </div>

      {/* 生成的简历预览 */}
      {generatedResume && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="font-semibold text-gray-900">生成的简历预览</h3>
            <div className="flex gap-2">
              <button
                onClick={() => {
                  navigator.clipboard.writeText(generatedResume)
                  alert('已复制到剪贴板')
                }}
                className="px-4 py-2 text-sm bg-gray-100 hover:bg-gray-200 rounded transition-colors"
              >
                📋 复制
              </button>
              <button
                onClick={() => handleExport('pdf')}
                className="px-4 py-2 text-sm bg-red-100 hover:bg-red-200 text-red-700 rounded transition-colors"
              >
                📄 导出 PDF
              </button>
              <button
                onClick={() => handleExport('word')}
                className="px-4 py-2 text-sm bg-blue-100 hover:bg-blue-200 text-blue-700 rounded transition-colors"
              >
                📝 导出 Word
              </button>
            </div>
          </div>
          <div className="bg-gray-50 rounded-lg p-6 whitespace-pre-wrap font-mono text-sm max-h-[600px] overflow-y-auto border">
            {generatedResume}
          </div>
        </div>
      )}
    </div>
  )
}

export default ResumeGenerator
